export type Status = "SUCCESS" | "PARTIAL" | "FAILED" | "SKIPPED" | "STARTED" | "PENDING";
export type RegimeName = "BULLISH" | "BEARISH" | "RANGE" | "NO_TRADE";

export interface OptionContract { id: number; strike: number; option_type: "CE" | "PE"; expiry: string; trading_symbol: string; instrument_token: string; ltp: number | null; open_interest: number | null; previous_open_interest: number | null; change_in_open_interest: number | null; volume: number | null; bid: number | null; ask: number | null; }
export interface MarketSnapshot { id: number; timestamp_ist: string; nifty_spot: number; nifty_future: number | null; india_vix: number | null; lot_size: number | null; atm_strike: number; expiry: string; source: string; options?: OptionContract[]; }
export interface ContractFeature { strike: number; option_type: "CE" | "PE"; open_interest: number | null; previous_open_interest: number | null; change_in_open_interest: number | null; volume: number | null; ltp: number | null; positioning_class: string; }
export interface MarketFeatures { snapshot_id: number; timestamp: string; expiry: string; spot: number; future: number | null; atm_strike: number; data_quality: { contracts_total: number; intraday_oi_usable: boolean; intraday_volume_usable: boolean; }; oi_features: { contracts: ContractFeature[] }; pcr_features: { local_pcr_oi: number | null; local_pcr_oi_change: number | null }; support_resistance: { potential_support_clusters: Array<{ center_strike: number }>; potential_resistance_clusters: Array<{ center_strike: number }> }; futures_features: { futures_basis: number | null; futures_basis_pct: number | null }; volatility_features: { india_vix: number | null; vix_regime: string | null }; price_structure_features: { spot_change_pct_from_previous_snapshot: number | null; session_open_proxy: number; collector_observed_high: number; collector_observed_low: number; vwap: null; vwap_available: false }; }
export interface MarketRegime { snapshot_id: number; timestamp: string; regime: RegimeName; bull_score: number; bear_score: number; range_score: number; confidence: number; evidence_quality: string; bull_evidence: string[]; bear_evidence: string[]; range_evidence: string[]; warnings: string[]; risk_flags: string[]; }
export interface AIResearch { snapshot_id: number; market_view?: string; confidence?: number; agreement_status?: string; bullish_evidence?: string[]; bearish_evidence?: string[]; range_evidence?: string[]; risks?: string[]; missing_evidence?: string[]; key_observations?: string[]; prompt_version: string; model: string; estimated_cost_usd?: number | null; status?: string; }
export interface CandidateLeg { strike: number; option_type: "CE" | "PE"; trading_symbol: string; ltp: number | null; bid: number | null; ask: number | null; open_interest: number | null; volume: number | null; }
export interface StrategyCandidate { candidate_id: string; strategy_type: string; short_leg: CandidateLeg; long_leg: CandidateLeg; spread_width: number; net_credit: number; credit_to_width_ratio: number; pricing_basis: "BID_ASK" | "LTP_ESTIMATE"; selection_score: number; support_or_resistance_reference: number | null; warnings: string[]; }
export interface StrategyCandidateSet { snapshot_id: number; eligible: boolean; strategy_type: string; candidate_count: number; candidates: StrategyCandidate[]; reason_codes: string[]; }
export interface RiskCheck { check_code: string; status: "PASS" | "FAIL" | "WARN" | "NOT_AVAILABLE"; actual_value: unknown; threshold: unknown; message: string; }
export interface RiskDecision { candidate_reference: string | null; decision: "APPROVED" | "REJECTED" | "NOT_APPLICABLE"; candidate_strategy: string; max_profit_per_lot: number | null; max_loss_per_lot: number | null; reward_to_risk_ratio: number | null; failed_checks: string[]; warnings: string[]; checks: RiskCheck[]; }
export interface RiskEvaluationSet { snapshot_id: number; approved_count: number; rejected_count: number; not_applicable: boolean; decisions: RiskDecision[]; }
export interface ShadowTrade { id: number; market_snapshot_id_entry: number; strategy_type: string; expiry: string; entry_timestamp: string; entry_spot: number; short_leg: CandidateLeg; long_leg: CandidateLeg; entry_credit: number; entry_pricing_basis: string; lot_size: number | null; max_profit_per_unit: number; max_loss_per_unit: number; max_profit_per_lot: number | null; max_loss_per_lot: number | null; status: "OPEN" | "CLOSED" | "INVALID"; exit_timestamp: string | null; exit_reason: string | null; exit_debit: number | null; realized_pnl_per_unit: number | null; realized_pnl_per_lot: number | null; mae_per_unit: number; mfe_per_unit: number; mae_per_lot: number | null; mfe_per_lot: number | null; holding_minutes: number | null; source_candidate: Record<string, unknown>; source_risk_decision: Record<string, unknown>; }
export interface ShadowMark { id: number | null; shadow_trade_id: number; market_snapshot_id: number; timestamp: string; exit_debit: number; pnl_per_unit: number; pnl_per_lot: number | null; spot: number; valuation_basis: string; }
export interface PipelineRun { id: number; market_snapshot_id: number; status: Status; feature_status: Status; regime_status: Status; ai_status: Status; strategy_status: Status; risk_status: Status; shadow_status: Status; approved_candidate_count: number; shadow_trade_id: number | null; started_at: string; completed_at: string | null; }
export type HealthStatus = "HEALTHY" | "DEGRADED" | "UNHEALTHY" | "UNKNOWN" | "IDLE";
export interface CompactSystemHealth { status: HealthStatus; current_time_ist: string; market_session_state: string; components: Record<string,string>; }
export interface DetailedSystemHealth {
  overall_status: HealthStatus; current_time_ist: string; market_session_state: string; components: Record<string,string>;
  database: {status:HealthStatus;latency_ms:number;safe_error_type:string|null;safe_error_message:string|null};
  collector: null | {heartbeat:{status:HealthStatus;worker_id:string|null;worker_status:string|null;last_heartbeat_at:string|null;age_seconds:number|null};data_freshness:{status:HealthStatus;last_snapshot_at:string|null;last_snapshot_id:number|null;age_seconds:number|null};runs_today:number;success_today:number;failed_today:number;success_rate_today:number|null;consecutive_failures:number;expected_snapshots_so_far_today:number;actual_snapshots_today:number;missing_snapshot_estimate:number};
  market_data: null | {status:HealthStatus;spot_available:boolean;future_available:boolean;vix_available:boolean;lot_size_available:boolean;option_contract_count:number;nonzero_volume_count:number;nonzero_oi_change_count:number;oi_current_prev_difference_count:number;oi_mismatch_count:number;intraday_oi_usable:boolean;bid_ask_coverage_pct:number|null;volume_coverage_pct:number|null;oi_change_coverage_pct:number|null};
  pipeline: null | {status:HealthStatus;latest_pipeline_status:string|null;runs_today:number;success_today:number;partial_today:number;failed_today:number;pipeline_success_rate_today:number|null;consecutive_failures:number;latest_stage_statuses:Record<string,string>;latest_stage_timings_ms:Record<string,number>;average_total_pipeline_ms:number|null;p95_total_pipeline_ms:number|null;average_stage_duration_ms:Record<string,number|null>;slowest_stage:string|null};
  shadow: null | {status:HealthStatus;open_shadow_trades:number;shadow_entries_today:number;shadow_exits_today:number;latest_shadow_mark_at:string|null;latest_mark_age_seconds:number|null;unavailable_marks_today:number;payout_anomalies_today:number;invalid_shadow_trades_today:number};
  ai: {status:string;model_configured?:boolean;calls_today?:number;cost_today_usd?:number;last_success_at?:string|null;last_failure_at?:string|null;last_latency_ms?:number|null};
  notifications: {telegram:{status:string;enabled:boolean;configured:boolean;last_sent_at:string|null;last_failed_at:string|null;failed_today:number;consecutive_failures?:number;deliveries_today?:number}};
}
export interface OperationalEvent {id:number;component:string;severity:string;event_code:string;safe_message:string;snapshot_id:number|null;pipeline_run_id:number|null;context:string|null;created_at:string}
export interface NotificationDelivery {id:number;channel:string;event_code:string;status:"PENDING"|"SENT"|"FAILED"|"SKIPPED";priority:"INFO"|"IMPORTANT"|"CRITICAL";subject_ref_type:string|null;subject_ref_id:string|null;attempt_count:number;last_attempt_at:string|null;sent_at:string|null;safe_error_type:string|null;safe_error_message:string|null;created_at:string;updated_at:string}
export interface SystemMetrics {date:string;snapshots_expected:number;snapshots_actual:number;snapshot_success_rate:number|null;collector_failures:number;pipeline_runs:number;pipeline_success_rate:number|null;avg_pipeline_ms:number|null;p95_pipeline_ms:number|null;db_latency_ms:number|null;shadow_entries:number;shadow_exits:number;ai_calls:number;ai_cost:number}
export interface DailyResearchSummary { date: string; snapshots_collected: number; snapshots_with_usable_oi: number; regime_counts: Record<RegimeName, number>; candidate_sets_created: number; approved_risk_decisions: number; rejected_risk_decisions: number; shadow_entries: number; shadow_exits: number; shadow_realized_pnl: number; open_shadow_trades: number; ai_calls: number; ai_cost: number; }
export interface PerformanceMetrics { trades: number; wins: number; losses: number; win_rate: number | null; gross_profit: number; gross_loss: number; net_pnl: number; average_win: number | null; average_loss: number | null; profit_factor: number | null; expectancy_per_trade: number | null; max_drawdown: number; }
export interface ShadowPerformance { total_trades: number; closed_trades: number; open_trades: number; invalid_trades: number; per_unit: PerformanceMetrics; per_lot: PerformanceMetrics; average_holding_minutes: number | null; average_mfe_per_unit: number | null; average_mae_per_unit: number | null; }
export interface DashboardData { snapshot: MarketSnapshot | null; features: MarketFeatures | null; regime: MarketRegime | null; ai_research: AIResearch | null; candidates: StrategyCandidateSet | null; risk: RiskEvaluationSet | null; open_shadow_trade: ShadowTrade | null; open_shadow_marks: ShadowMark[]; open_shadow_thresholds: { profit_target_pnl_per_unit: number; stop_loss_pnl_per_unit: number; force_exit_time: string } | null; shadow_trades: ShadowTrade[]; pipeline: PipelineRun | null; pipeline_health: { last_success: PipelineRun | null; last_partial: PipelineRun | null; last_failed: PipelineRun | null }; daily_summary: DailyResearchSummary; regime_history: MarketRegime[]; shadow_performance: ShadowPerformance; shadow_breakdown: Record<string, Record<string, ShadowPerformance>>; system: { database_api: string; collector_interval_minutes: number; collector_start_time: string; collector_end_time: string; ai_research_configured: boolean; server_time_ist: string }; }
