export interface CreditSpreadEconomics {
  strategy_logic_version?: string | null; strategy_family?: string | null; market_bias?: string | null;
  directional_strength?: string | null; survival_score?: number | null; carry_score?: number | null;
  expected_move_source?: string | null; expected_move_points?: number | null;
  distance_in_expected_move_units?: number | null; days_to_expiry?: number | null; dte_bucket?: string | null;
  gamma_risk_state?: string | null; theta_gamma_balance_state?: string | null;
  max_loss_per_lot?: number | null; required_short_strike_buffer?: number | null;
  distance_beyond_structure_points?: number | null; estimated_cost?: number | null;
  net_credit_after_cost?: number | null; cost_estimate_complete?: boolean;
  survival_components?: Record<string, number>; carry_components?: Record<string, number>;
  ranking_components?: Record<string, number>; ranking_penalties?: Record<string, number>;
}
export type Status = "SUCCESS" | "PARTIAL" | "FAILED" | "SKIPPED" | "STARTED" | "PENDING";
export type RegimeName = "BULLISH" | "BEARISH" | "RANGE" | "NO_TRADE";

export interface OptionContract { id: number; strike: number; option_type: "CE" | "PE"; expiry: string; trading_symbol: string; instrument_token: string; exchange?: string | null; source_market_timestamp?: string | null; bid_quantity?: number | null; ask_quantity?: number | null; depth_unit?: "UNKNOWN" | "UNITS" | "LOTS"; tick_size?: number | null; ltp: number | null; open_interest: number | null; previous_open_interest: number | null; change_in_open_interest: number | null; volume: number | null; bid: number | null; ask: number | null; }
export interface MarketSnapshot { id: number; timestamp_ist: string; nifty_spot: number; nifty_future: number | null; india_vix: number | null; lot_size: number | null; atm_strike: number; expiry: string; source: string; source_market_timestamp?: string | null; request_started_at?: string | null; response_received_at?: string | null; options?: OptionContract[]; }
export interface ContractFeature { strike: number; option_type: "CE" | "PE"; open_interest: number | null; previous_open_interest: number | null; change_in_open_interest: number | null; volume: number | null; ltp: number | null; positioning_class: string; }
export interface MarketFeatures { snapshot_id: number; timestamp: string; expiry: string; spot: number; future: number | null; atm_strike: number; data_quality: { contracts_total: number; intraday_oi_usable: boolean; intraday_volume_usable: boolean; }; oi_features: { contracts: ContractFeature[] }; pcr_features: { local_pcr_oi: number | null; local_pcr_oi_change: number | null }; support_resistance: { potential_support_clusters: Array<{ center_strike: number }>; potential_resistance_clusters: Array<{ center_strike: number }> }; futures_features: { futures_basis: number | null; futures_basis_pct: number | null }; volatility_features: { india_vix: number | null; vix_regime: string | null }; price_structure_features: { spot_change_pct_from_previous_snapshot: number | null; session_open_proxy: number; collector_observed_high: number; collector_observed_low: number; vwap: null; vwap_available: false }; }
export interface MarketRegime { market_bias?: string | null; directional_strength?: string | null; strategy_family_eligibility?: string | null; snapshot_id: number; timestamp: string; regime: RegimeName; bull_score: number; bear_score: number; range_score: number; confidence: number; evidence_quality: string; bull_evidence: string[]; bear_evidence: string[]; range_evidence: string[]; warnings: string[]; risk_flags: string[]; signal_groups?: Array<{name:string;direction:string;score:number;reason_codes:string[]}>; }
export interface AlphaFeature { snapshot_id:number;timestamp:string;expiry:string;price_source:string;price_return:number|null;alpha_1:number|null;alpha_2:number|null;alpha_1_direction:string;alpha_2_direction:string;joint_alpha_direction:string;consecutive_confirmation_count:number;confirmed:boolean;evidence_quality:string;status:string;atm_volume_activity:number|null;atm_option_volatility:number|null;warnings:string[];session_id?:string|null;hypothesis_type?:string;lookback_clock_mode?:string;validity_state?:string;participation_state?:string;underlying_horizon_volatility?:number|null;actual_horizon_seconds?:number|null;signed_log_return?:number|null;confirmation_reset_reason?:string|null;legacy_alpha2_raw?:number|null;ce_volume_state?:string;pe_volume_state?:string;standardized_return?:number|null; }
export interface AIResearch { snapshot_id: number; market_view?: string; confidence?: number; agreement_status?: string; bullish_evidence?: string[]; bearish_evidence?: string[]; range_evidence?: string[]; risks?: string[]; missing_evidence?: string[]; key_observations?: string[]; prompt_version: string; model: string; estimated_cost_usd?: number | null; status?: string; }
export interface CandidateLeg { strike: number; option_type: "CE" | "PE"; trading_symbol: string; ltp: number | null; bid: number | null; ask: number | null; open_interest: number | null; volume: number | null; }
export interface StrategyCandidate extends CreditSpreadEconomics { candidate_id: string; strategy_type: string; short_leg: CandidateLeg; long_leg: CandidateLeg; spread_width: number; net_credit: number; credit_to_width_ratio: number; pricing_basis: "BID_ASK" | "LTP_ESTIMATE"; selection_score: number; support_or_resistance_reference: number | null; warnings: string[]; }
export interface StrategyCandidateSet { snapshot_id: number; eligible: boolean; strategy_type: string; candidate_count: number; candidates: StrategyCandidate[]; reason_codes: string[]; strategy_version?: string | null; strategy_logic_version?: string | null; execution_mode?: string | null; created_at?: string | null; }
export interface RiskCheck { check_code: string; status: "PASS" | "FAIL" | "WARN" | "NOT_AVAILABLE"; actual_value: unknown; threshold: unknown; message: string; }
export interface RiskDecision { candidate_reference: string | null; decision: "APPROVED" | "REJECTED" | "NOT_APPLICABLE"; candidate_strategy: string; max_profit_per_lot: number | null; max_loss_per_lot: number | null; reward_to_risk_ratio: number | null; failed_checks: string[]; reason_codes?: string[]; warnings: string[]; checks: RiskCheck[]; }
export interface RiskEvaluationSet { snapshot_id: number; approved_count: number; rejected_count: number; not_applicable: boolean; decisions: RiskDecision[]; strategy_version?: string | null; execution_mode?: string | null; created_at?: string | null; }
export interface ShadowTrade extends CreditSpreadEconomics { id: number; market_snapshot_id_entry: number; strategy_type: string; expiry: string; entry_timestamp: string; entry_spot: number; short_leg: CandidateLeg; long_leg: CandidateLeg; entry_credit: number; entry_pricing_basis: string; lot_size: number | null; max_profit_per_unit: number; max_loss_per_unit: number; max_profit_per_lot: number | null; max_loss_per_lot: number | null; entry_alpha_1?:number|null;entry_alpha_2?:number|null;entry_joint_alpha_direction?:string|null;entry_alpha_evidence_quality?:string|null;entry_alpha_confirmation_count?:number; status: "OPEN" | "CLOSED" | "INVALID"; exit_timestamp: string | null; exit_reason: string | null; exit_debit: number | null; realized_pnl_per_unit: number | null; realized_pnl_per_lot: number | null; mae_per_unit: number; mfe_per_unit: number; mae_per_lot: number | null; mfe_per_lot: number | null; holding_minutes: number | null; source_candidate: Record<string, unknown>; source_risk_decision: Record<string, unknown>; }
export interface ShadowMark { id: number | null; shadow_trade_id: number; market_snapshot_id: number; timestamp: string; exit_debit: number; pnl_per_unit: number; pnl_per_lot: number | null; spot: number; valuation_basis: string; }
export interface PipelineRun { id: number; market_snapshot_id: number; status: Status; feature_status: Status; alpha_status?: Status; regime_status: Status; ai_status: Status; strategy_status: Status; risk_status: Status; shadow_status: Status; approved_candidate_count: number; shadow_trade_id: number | null; started_at: string; completed_at: string | null; }
export type HealthStatus = "HEALTHY" | "DEGRADED" | "UNHEALTHY" | "UNKNOWN" | "IDLE";
export interface CompactSystemHealth { status: HealthStatus; current_time_ist: string; market_session_state: string; components: Record<string,string>; }
export interface DetailedSystemHealth {
  overall_status: HealthStatus; current_time_ist: string; market_session_state: string; components: Record<string,string>;
  database: {status:HealthStatus;latency_ms:number;safe_error_type:string|null;safe_error_message:string|null};
  collector: null | {heartbeat:{status:HealthStatus;worker_id:string|null;worker_status:string|null;last_heartbeat_at:string|null;age_seconds:number|null};data_freshness:{status:HealthStatus;last_snapshot_at:string|null;last_snapshot_id:number|null;age_seconds:number|null};runs_today:number;success_today:number;failed_today:number;success_rate_today:number|null;consecutive_failures:number;expected_snapshots_so_far_today:number;actual_snapshots_today:number;missing_snapshot_estimate:number};
  market_data: null | {status:HealthStatus;spot_available:boolean;future_available:boolean;vix_available:boolean;lot_size_available:boolean;option_contract_count:number;nonzero_volume_count:number;nonzero_oi_change_count:number;oi_current_prev_difference_count:number;oi_mismatch_count:number;intraday_oi_usable:boolean;bid_ask_coverage_pct:number|null;volume_coverage_pct:number|null;oi_change_coverage_pct:number|null};
  pipeline: null | {status:HealthStatus;latest_pipeline_status:string|null;runs_today:number;success_today:number;partial_today:number;failed_today:number;pipeline_success_rate_today:number|null;consecutive_failures:number;latest_stage_statuses:Record<string,string>;latest_stage_timings_ms:Record<string,number>;average_total_pipeline_ms:number|null;p95_total_pipeline_ms:number|null;average_stage_duration_ms:Record<string,number|null>;slowest_stage:string|null};
  shadow: null | {status:HealthStatus;open_shadow_trades:number;shadow_entries_today:number;shadow_exits_today:number;latest_shadow_mark_at:string|null;latest_mark_age_seconds:number|null;unavailable_marks_today:number;payout_anomalies_today:number;invalid_shadow_trades_today:number};
  ai: {status:string;model_configured?:boolean;calls_today?:number;cost_today_usd?:number;last_success_at?:string|null;last_failure_at?:string|null;last_latency_ms?:number|null};
  notifications: {telegram:{status:string;enabled:boolean;configured:boolean;last_sent_at:string|null;last_failed_at:string|null;failed_today:number;consecutive_failures?:number;deliveries_today?:number}};
}
export interface OperationalEvent {id:number;component:string;severity:string;event_code:string;safe_message:string;snapshot_id:number|null;pipeline_run_id:number|null;context:string|null;created_at:string}
export interface NotificationDelivery {id:number;channel:string;event_code:string;status:"PENDING"|"SENT"|"FAILED"|"SKIPPED";priority:"INFO"|"IMPORTANT"|"CRITICAL";subject_ref_type:string|null;subject_ref_id:string|null;attempt_count:number;last_attempt_at:string|null;sent_at:string|null;safe_error_type:string|null;safe_error_message:string|null;created_at:string;updated_at:string}
export interface SystemMetrics {date:string;snapshots_expected:number;snapshots_actual:number;snapshot_success_rate:number|null;collector_failures:number;pipeline_runs:number;pipeline_success_rate:number|null;avg_pipeline_ms:number|null;p95_pipeline_ms:number|null;db_latency_ms:number|null;shadow_entries:number;shadow_exits:number;ai_calls:number;ai_cost:number}
export interface DailyResearchSummary { date: string; snapshots_collected: number; snapshots_with_usable_oi: number; regime_counts: Record<RegimeName, number>; candidate_sets_created: number; approved_risk_decisions: number; rejected_risk_decisions: number; shadow_entries: number; shadow_exits: number; shadow_realized_pnl: number; open_shadow_trades: number; ai_calls: number; ai_cost: number; }
export interface PerformanceMetrics { trades: number; wins: number; losses: number; win_rate: number | null; gross_profit: number; gross_loss: number; net_pnl: number; average_win: number | null; average_loss: number | null; profit_factor: number | null; expectancy_per_trade: number | null; max_drawdown: number; }
export interface ShadowPerformance { total_trades: number; closed_trades: number; open_trades: number; invalid_trades: number; per_unit: PerformanceMetrics; per_lot: PerformanceMetrics; average_holding_minutes: number | null; average_mfe_per_unit: number | null; average_mae_per_unit: number | null; }
export interface ForwardPaperSummary { pending: number; open: number; closed: number; unresolved: number; rejected: number; profitability_claim: false; }
export interface ScalperSignal { timestamp:string;direction:"BULL"|"BEAR"|"NEUTRAL";strength:string;score:number;components:Record<string,number>;contradiction_penalty:number;reasons:string[];warnings:string[];confirmation_count:number;confirmed:boolean; }
export interface ScalperPosition { state?:string;decision_timestamp:string;entry_timestamp?:string;entry_credit?:number;current_debit?:number;gross_mark_rupees?:number;holding_seconds?:number;exit_reason?:string;rejection_reason?:string;cost_completeness:string;candidate:{strategy_type:string;short_leg:{strike:number;option_type:string;trading_symbol:string};long_leg:{strike:number;option_type:string;trading_symbol:string};defined_max_loss_per_lot:number;broker_margin:null}; }
export interface ScalperSummary { enabled:boolean;mode:"PAPER";schema_ready:boolean;interval_seconds:number;kill_switch:boolean;score_threshold:number;minimum_confirmations:number;latest_snapshot?:null|{id:number;timestamp:string;spot:number;signal:ScalperSignal;features:{executable_book_coverage:number;median_spread_pct:number|null}};current_position?:ScalperPosition|null;today?:{trades:number;wins:number;losses:number;gross_pnl:number;rejections:number;cost_completeness:"GROSS_ONLY";net_pnl:null;profitability_claim:false};timeline?:Array<{event_type:string;market_timestamp:string;state:string|null;trigger?:string;reason?:string}>; }
export interface DashboardData { execution_mode?: string | null; forward_paper?: ForwardPaperSummary | null; scalper?:ScalperSummary; snapshot: MarketSnapshot | null; features: MarketFeatures | null; alpha?: AlphaFeature | null; alpha_history?: AlphaFeature[]; regime: MarketRegime | null; ai_research: AIResearch | null; candidates: StrategyCandidateSet | null; risk: RiskEvaluationSet | null; open_shadow_trade: ShadowTrade | null; open_shadow_marks: ShadowMark[]; open_shadow_thresholds: { profit_target_pnl_per_unit: number; stop_loss_pnl_per_unit: number; force_exit_time: string } | null; shadow_trades: ShadowTrade[]; pipeline: PipelineRun | null; pipeline_health: { last_success: PipelineRun | null; last_partial: PipelineRun | null; last_failed: PipelineRun | null }; daily_summary: DailyResearchSummary; regime_history: MarketRegime[]; shadow_performance: ShadowPerformance; shadow_breakdown: Record<string, Record<string, ShadowPerformance>>; system: { database_api: string; collector_interval_minutes: number; collector_start_time: string; collector_end_time: string; ai_research_configured: boolean; server_time_ist: string }; }
