"use client";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { ContractFeature, ShadowMark, ShadowTrade } from "@/types";
import { number, timeIST } from "@/lib/format";

export function OIChart({ contracts, mode, atm, support, resistance }: { contracts: ContractFeature[]; mode: "OI" | "DOI"; atm: number; support?: number; resistance?: number }) {
  const byStrike = new Map<number, { strike: number; call: number; put: number }>();
  contracts.forEach((row) => { const item = byStrike.get(row.strike) ?? { strike: row.strike, call: 0, put: 0 }; const value = mode === "OI" ? row.open_interest : row.change_in_open_interest; item[row.option_type === "CE" ? "call" : "put"] = value ?? 0; byStrike.set(row.strike, item); });
  const data = [...byStrike.values()].sort((a,b) => a.strike-b.strike);
  return <div className="chart" aria-label={`${mode} by strike chart`}><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ top:10,right:10,left:5,bottom:5 }}><CartesianGrid stroke="#192633" vertical={false}/><XAxis dataKey="strike" stroke="#5f7283" fontSize={11}/><YAxis stroke="#5f7283" fontSize={11} tickFormatter={(v) => Intl.NumberFormat("en-IN",{notation:"compact"}).format(v)}/><Tooltip contentStyle={{background:"#111e2a",border:"1px solid #22303d",borderRadius:2}} formatter={(v) => number(Number(v),0)}/><ReferenceLine x={atm} stroke="#eaf0f5" strokeDasharray="3 3" label={{value:"ATM",fill:"#8fa3b5",fontSize:10}}/>{support && <ReferenceLine x={support} stroke="#2fb67c"/>}{resistance && <ReferenceLine x={resistance} stroke="#e15b64"/>}<Bar dataKey="call" name="Call" fill="#e15b64" opacity={.82}/><Bar dataKey="put" name="Put" fill="#2fb67c" opacity={.82}/></BarChart></ResponsiveContainer></div>;
}
export function PnlChart({ marks, thresholds }: { marks: ShadowMark[]; trade?: ShadowTrade; thresholds?: { profit_target_pnl_per_unit: number; stop_loss_pnl_per_unit: number } | null }) { const data=marks.map(m=>({time:timeIST(m.timestamp).replace(" IST",""),pnl:m.pnl_per_unit})); return <div className="chart-sm" aria-label="Shadow profit and loss path"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid stroke="#192633"/><XAxis dataKey="time" stroke="#5f7283" fontSize={10}/><YAxis stroke="#5f7283" fontSize={11}/><Tooltip contentStyle={{background:"#111e2a",border:"1px solid #22303d"}}/><ReferenceLine y={0} stroke="#8fa3b5"/>{thresholds&&<ReferenceLine y={thresholds.profit_target_pnl_per_unit} stroke="#2fb67c" strokeDasharray="4 4"/>}{thresholds&&<ReferenceLine y={thresholds.stop_loss_pnl_per_unit} stroke="#e15b64" strokeDasharray="4 4"/>}<Line dataKey="pnl" name="P&L / unit" stroke="#4d8fd8" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div>; }
export function EquityChart({ values, drawdown=false }: { values: number[]; drawdown?: boolean }) { const data=values.reduce<Array<{trade:number;value:number;equity:number;peak:number}>>((rows,value,index)=>{const prior=rows.at(-1);const equity=(prior?.equity??0)+value;const peak=Math.max(prior?.peak??0,equity);return [...rows,{trade:index+1,value:drawdown?equity-peak:equity,equity,peak}];},[]); return <div className="chart-sm"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid stroke="#192633"/><XAxis dataKey="trade" stroke="#5f7283"/><YAxis stroke="#5f7283"/><Tooltip contentStyle={{background:"#111e2a",border:"1px solid #22303d"}}/><ReferenceLine y={0} stroke="#5f7283"/><Line dataKey="value" stroke={drawdown?"#e15b64":"#2fb67c"} dot={false} strokeWidth={2}/></LineChart></ResponsiveContainer></div>; }
export function BreakdownChart({ data }: { data: Array<{ name: string; wins: number; losses: number }> }) { return <div className="chart-sm"><ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid stroke="#192633" vertical={false}/><XAxis dataKey="name" stroke="#5f7283" fontSize={10}/><YAxis stroke="#5f7283"/><Tooltip contentStyle={{background:"#111e2a",border:"1px solid #22303d"}}/><Bar dataKey="wins" fill="#2fb67c"/><Bar dataKey="losses" fill="#e15b64"/></BarChart></ResponsiveContainer></div>; }
