"use client";
import { useCallback } from "react";
import { api } from "@/lib/api";
import { usePolling } from "@/hooks/use-polling";
import { timeIST } from "@/lib/format";
import { Badge, Empty, Panel, SectionError } from "@/components/ui";
import type { DetailedSystemHealth, NotificationDelivery, OperationalEvent, SystemMetrics } from "@/types";

const value=(item:number|null|undefined,suffix="")=>item==null?"N/A":`${item.toLocaleString()}${suffix}`;
const availability=(item:boolean)=>item?"HEALTHY":"UNAVAILABLE";
function Cells({items}:{items:Array<[string,React.ReactNode]>}){return <div className="kv-grid">{items.map(([label,item])=><div className="kv" key={label}><dt>{label}</dt><dd>{item}</dd></div>)}</div>}
function StageTable({health}:{health:DetailedSystemHealth}){const pipeline=health.pipeline;if(!pipeline)return <Empty>NO PIPELINE HEALTH</Empty>;const names=["shadow_pre_update","features","regime","ai","strategy","risk","shadow_entry","total_pipeline"];return <div className="table-wrap"><table><thead><tr><th>Stage</th><th>Status</th><th>Latest ms</th><th>Average ms</th></tr></thead><tbody>{names.map(name=><tr key={name}><td>{name.replaceAll("_"," ")}</td><td>{name==="total_pipeline"?pipeline.latest_pipeline_status:<Badge value={pipeline.latest_stage_statuses[name.replace("features","feature").replace("shadow_pre_update","shadow").replace("shadow_entry","shadow")]??"N/A"}/>}</td><td>{value(pipeline.latest_stage_timings_ms[name])}</td><td>{value(pipeline.average_stage_duration_ms[name])}</td></tr>)}</tbody></table></div>}

export function SystemHealth(){
 const loader=useCallback(async()=>{const[health,events,metrics,notifications]=await Promise.all([api.systemHealth(),api.systemEvents(),api.systemMetrics(),api.notifications()]);return{health,events,metrics,notifications}},[]);
 const{data,error,loading}=usePolling(loader,30000);
 if(error&&!data)return <main><div className="page-head"><div><h1>System Operations</h1><p>Read-only observability console</p></div></div><SectionError>BACKEND HEALTH API UNAVAILABLE</SectionError></main>;
 if(loading&&!data)return <main><div className="loading">CHECKING SYSTEM</div></main>;
 if(!data)return null;
 const{health,events,metrics,notifications}=data as {health:DetailedSystemHealth;events:OperationalEvent[];metrics:SystemMetrics;notifications:NotificationDelivery[]};
 return <main><div className="page-head"><div><h1>System Operations</h1><p>Read-only health, cadence, quality, and failure visibility</p></div><div className="health-head"><Badge value={health.overall_status}/><span>{health.market_session_state}</span><span>{timeIST(health.current_time_ist)}</span></div></div>
 <div className="status-strip">{Object.entries(health.components).map(([name,status])=><div className="status-item" key={name}><span>{name.replaceAll("_"," ")}</span><Badge value={status}/></div>)}</div>
 <div className="grid grid-2 operations-grid">
 <Panel title="Collector & freshness"><Cells items={[["Heartbeat",<Badge key="h" value={health.collector?.heartbeat.status??"UNKNOWN"}/>],["Worker",health.collector?.heartbeat.worker_status??"N/A"],["Heartbeat age",value(health.collector?.heartbeat.age_seconds,"s")],["Last snapshot",timeIST(health.collector?.data_freshness.last_snapshot_at)],["Data age",value(health.collector?.data_freshness.age_seconds,"s")],["Expected / actual",`${metrics.snapshots_expected} / ${metrics.snapshots_actual}`],["Missing estimate",value(health.collector?.missing_snapshot_estimate)],["Success rate",value(health.collector?.success_rate_today,"%")],["Failures",value(health.collector?.failed_today)]]}/></Panel>
 <Panel title="Database"><Cells items={[["Status",<Badge key="db" value={health.database.status}/>],["Query latency",value(health.database.latency_ms," ms")],["Safe error",health.database.safe_error_message??"NONE"]]}/></Panel>
 <Panel title="Market data quality"><Cells items={[["Spot",availability(health.market_data?.spot_available??false)],["Future",availability(health.market_data?.future_available??false)],["India VIX",availability(health.market_data?.vix_available??false)],["Lot size",availability(health.market_data?.lot_size_available??false)],["Contracts",value(health.market_data?.option_contract_count)],["Intraday OI",health.market_data?.intraday_oi_usable?"USABLE":"UNUSABLE"],["Nonzero volume",value(health.market_data?.nonzero_volume_count)],["Nonzero OI change",value(health.market_data?.nonzero_oi_change_count)],["OI mismatch",value(health.market_data?.oi_mismatch_count)],["Bid/ask coverage",value(health.market_data?.bid_ask_coverage_pct,"%")],["Volume coverage",value(health.market_data?.volume_coverage_pct,"%")],["OI change coverage",value(health.market_data?.oi_change_coverage_pct,"%")]]}/></Panel>
 <Panel title="Shadow engine"><Cells items={[["Status",<Badge key="s" value={health.shadow?.status??"UNKNOWN"}/>],["Open trades",value(health.shadow?.open_shadow_trades)],["Entries / exits",`${metrics.shadow_entries} / ${metrics.shadow_exits}`],["Latest mark",timeIST(health.shadow?.latest_shadow_mark_at)],["Unavailable marks",value(health.shadow?.unavailable_marks_today)],["Payout anomalies",value(health.shadow?.payout_anomalies_today)],["Invalid trades",value(health.shadow?.invalid_shadow_trades_today)]]}/></Panel>
 <Panel title="Pipeline performance" className="span-2"><div className="metric-strip ops-metrics"><div className="metric"><div className="metric-label">Status</div><div className="metric-value"><Badge value={health.pipeline?.status??"UNKNOWN"}/></div></div><div className="metric"><div className="metric-label">Runs</div><div className="metric-value">{metrics.pipeline_runs}</div></div><div className="metric"><div className="metric-label">Success</div><div className="metric-value">{value(metrics.pipeline_success_rate,"%")}</div></div><div className="metric"><div className="metric-label">Average</div><div className="metric-value">{value(metrics.avg_pipeline_ms," ms")}</div></div><div className="metric"><div className="metric-label">P95</div><div className="metric-value">{value(metrics.p95_pipeline_ms," ms")}</div></div><div className="metric"><div className="metric-label">Failures</div><div className="metric-value">{value(health.pipeline?.failed_today)}</div></div></div><StageTable health={health}/></Panel>
 <Panel title="AI research"><Cells items={[["State",<Badge key="a" value={health.ai.status}/>],["Model configured",health.ai.model_configured?"YES":"NO"],["Calls today",value(health.ai.calls_today)],["Last success",timeIST(health.ai.last_success_at)],["Last failure",timeIST(health.ai.last_failure_at)],["Last latency",value(health.ai.last_latency_ms," ms")],["Cost today",health.ai.cost_today_usd==null?"N/A":`$${health.ai.cost_today_usd}`]]}/><p className="metric-detail">No paid provider probe is made by this page.</p></Panel>
 <Panel title="Notifications"><Cells items={[["Telegram",health.notifications.telegram.enabled?"ENABLED":"DISABLED"],["Status",<Badge key="tg" value={health.notifications.telegram.status}/>],["Configured",health.notifications.telegram.configured?"YES":"NO"],["Last sent",timeIST(health.notifications.telegram.last_sent_at)],["Last failure",timeIST(health.notifications.telegram.last_failed_at)],["Failed today",value(health.notifications.telegram.failed_today)]]}/><p className="metric-detail">Outbound only. Credentials and message content are never shown here.</p></Panel>
 <Panel title="Recent notification deliveries" className="span-2">{notifications.length?<div className="table-wrap"><table><thead><tr><th>Time</th><th>Event</th><th>Priority</th><th>Status</th><th>Subject</th><th>Attempts</th></tr></thead><tbody>{notifications.map(item=><tr key={item.id}><td>{timeIST(item.created_at)}</td><td>{item.event_code}</td><td><Badge value={item.priority}/></td><td><Badge value={item.status}/></td><td>{item.subject_ref_type&&item.subject_ref_id?`${item.subject_ref_type}: ${item.subject_ref_id}`:"—"}</td><td>{item.attempt_count}</td></tr>)}</tbody></table></div>:<Empty>NO NOTIFICATION DELIVERIES</Empty>}</Panel>
 <Panel title="Recent operational events" className="span-2">{events.length?<div className="table-wrap"><table><thead><tr><th>Time</th><th>Severity</th><th>Component</th><th>Event</th><th>Message</th><th>Snapshot</th></tr></thead><tbody>{events.map(event=><tr key={event.id}><td>{timeIST(event.created_at)}</td><td><Badge value={event.severity}/></td><td>{event.component}</td><td>{event.event_code}</td><td className="event-message">{event.safe_message}</td><td>{event.snapshot_id??"—"}</td></tr>)}</tbody></table></div>:<Empty>NO OPERATIONAL EVENTS</Empty>}</Panel>
 </div></main>;
}
