import { cleanup, render, screen } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { SystemHealth } from "@/components/system-health";
import { api } from "@/lib/api";
import type { DetailedSystemHealth, SystemMetrics } from "@/types";

vi.mock("@/lib/api", async (original) => ({
  ...(await original<typeof import("@/lib/api")>()),
  api: { systemHealth:vi.fn(), systemEvents:vi.fn(), systemMetrics:vi.fn(), notifications:vi.fn() },
}));
afterEach(cleanup);

function fixture(status:"HEALTHY"|"DEGRADED"|"UNHEALTHY"="HEALTHY"):DetailedSystemHealth{return {overall_status:status,current_time_ist:"2026-10-05T10:00:00+05:30",market_session_state:"OPEN",components:{database:"HEALTHY",collector_heartbeat:status,data_freshness:"HEALTHY",market_data:"HEALTHY",pipeline:"HEALTHY",shadow:"IDLE",ai:"DISABLED",notifications:"HEALTHY"},database:{status:"HEALTHY",latency_ms:2,safe_error_type:null,safe_error_message:null},collector:{heartbeat:{status,worker_id:"collector-main",worker_status:"RUNNING",last_heartbeat_at:"2026-10-05T09:59:55+05:30",age_seconds:5},data_freshness:{status:"HEALTHY",last_snapshot_at:"2026-10-05T09:59:00+05:30",last_snapshot_id:481,age_seconds:60},runs_today:15,success_today:14,failed_today:1,success_rate_today:93.33,consecutive_failures:0,expected_snapshots_so_far_today:15,actual_snapshots_today:14,missing_snapshot_estimate:1},market_data:{status:"HEALTHY",spot_available:true,future_available:true,vix_available:true,lot_size_available:true,option_contract_count:42,nonzero_volume_count:30,nonzero_oi_change_count:20,oi_current_prev_difference_count:20,oi_mismatch_count:0,intraday_oi_usable:true,bid_ask_coverage_pct:90,volume_coverage_pct:100,oi_change_coverage_pct:100},pipeline:{status:"HEALTHY",latest_pipeline_status:"SUCCESS",runs_today:14,success_today:14,partial_today:0,failed_today:0,pipeline_success_rate_today:100,consecutive_failures:0,latest_stage_statuses:{feature:"SUCCESS",regime:"SUCCESS",ai:"SKIPPED",strategy:"SUCCESS",risk:"SUCCESS",shadow:"SUCCESS"},latest_stage_timings_ms:{features:12,total_pipeline:60},average_total_pipeline_ms:55,p95_total_pipeline_ms:70,average_stage_duration_ms:{features:11},slowest_stage:"features"},shadow:{status:"IDLE",open_shadow_trades:0,shadow_entries_today:0,shadow_exits_today:0,latest_shadow_mark_at:null,latest_mark_age_seconds:null,unavailable_marks_today:0,payout_anomalies_today:0,invalid_shadow_trades_today:0},ai:{status:"DISABLED",model_configured:false,calls_today:0,cost_today_usd:0,last_success_at:null,last_failure_at:null,last_latency_ms:null},notifications:{telegram:{status:"HEALTHY",enabled:true,configured:true,last_sent_at:"2026-10-05T09:58:00+05:30",last_failed_at:null,failed_today:0}}}}
const metrics:SystemMetrics={date:"2026-10-05",snapshots_expected:15,snapshots_actual:14,snapshot_success_rate:93.33,collector_failures:1,pipeline_runs:14,pipeline_success_rate:100,avg_pipeline_ms:55,p95_pipeline_ms:70,db_latency_ms:2,shadow_entries:0,shadow_exits:0,ai_calls:0,ai_cost:0};
async function show(status:"HEALTHY"|"DEGRADED"|"UNHEALTHY"="HEALTHY"){vi.mocked(api.systemHealth).mockResolvedValue(fixture(status));vi.mocked(api.systemEvents).mockResolvedValue([{id:1,component:"MARKET_DATA",severity:"WARN",event_code:"VIX_MISSING",safe_message:"India VIX unavailable",snapshot_id:481,pipeline_run_id:null,context:null,created_at:"2026-10-05T09:42:05+05:30"}]);vi.mocked(api.systemMetrics).mockResolvedValue(metrics);vi.mocked(api.notifications).mockResolvedValue([{id:9,channel:"TELEGRAM",event_code:"RISK_APPROVED",status:"SENT",priority:"IMPORTANT",subject_ref_type:"risk_decision",subject_ref_id:"12",attempt_count:1,last_attempt_at:"2026-10-05T09:58:00+05:30",sent_at:"2026-10-05T09:58:00+05:30",safe_error_type:null,safe_error_message:null,created_at:"2026-10-05T09:58:00+05:30",updated_at:"2026-10-05T09:58:00+05:30"}]);render(<SystemHealth/>);await screen.findByText("System Operations")}

it.each(["HEALTHY","DEGRADED","UNHEALTHY"] as const)("renders %s system state",async status=>{await show(status);expect(screen.getAllByText(status).length).toBeGreaterThan(0)});
it("renders safe operational events",async()=>{await show();expect(screen.getByText("VIX_MISSING")).toBeInTheDocument();expect(screen.getByText("India VIX unavailable")).toBeInTheDocument();expect(screen.queryByText(/stack trace|api key/i)).not.toBeInTheDocument()});
it("renders market-data quality",async()=>{await show();expect(screen.getByText("42")).toBeInTheDocument();expect(screen.getByText("USABLE")).toBeInTheDocument();expect(screen.getByText("90%")).toBeInTheDocument()});
it("renders pipeline timings without execution controls",async()=>{await show();expect(screen.getByText("60")).toBeInTheDocument();expect(screen.queryByRole("button",{name:/buy|sell|order/i})).not.toBeInTheDocument()});
it("renders Telegram status and delivery history",async()=>{await show();expect(screen.getByText("ENABLED")).toBeInTheDocument();expect(screen.getByText("RISK_APPROVED")).toBeInTheDocument();expect(screen.getByText("risk_decision: 12")).toBeInTheDocument()});
it("never renders Telegram credentials",async()=>{await show();expect(screen.queryByText(/bot token|chat id|123456:secret/i)).not.toBeInTheDocument()});
